### ISSUE TITLE
Question / Error regarding the new disconnect on zombie part

### ISSUE THREAD

**Issue by dakovi** [jaggedsoft/node-binance-api#102]
Hello,

v0.4.12 is getting me some headaches because of the heartbeat implemenation. I am currently using a combined websocket stream with the "reconnect: false" option for kline data. My script terminates the stream from time to time when one coinpair isn't of interest anymore with the following code:

binance.websockets.terminate(endpoint);

That has worked out fine till 0.4.12 arrived. The newly implemented interval doesn't seem to be cleared by a "manual" websocket termination. I guess it is therefore trying to terminate a "zombie" socket which (because of my order some seconds before the interval iteration) doesn't exist anymore. The corresponding error:

...\node_modules\node-binance-api\node_modules\ws\lib\WebSocket.js:308
      throw new Error('not opened');
      ^

Error: not opened
    at WebSocket.ping (C:\Users\Daniel\node\node_modules\node-binance-api\node_modules\ws\lib\WebSocket.js:308:13)
    at Timeout.ping [as _onTimeout] (C:\Users\Daniel\node\node_modules\node-binance-api\node-binance-api.js:286:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

I am not much of a coding guy so sorry for any mistakes but maybe you understand the problem or see any errors or comprohension problems on my side that could help out.

Regards

**Comment by jaggedsoft** [comment]
Hi, thanks for the report!
I'll disable this feature if reconnect is set to false. Issuing a new release shortly

**Comment by jaggedsoft** [comment]
Available in `v0.4.13` https://github.com/jaggedsoft/node-binance-api/commit/25cafa630d3e52f445f3efb2cf0a9620074ffc6a

**Comment by keith1024** [comment]
Hey @jaggedsoft, sorry to reopen this. I saw this issue last night, and wanted to comment then, but it was really late and I was too tired to trust my judgement. 💤

@dakovi is correct in that the interval is not being cleared properly when the socket is manually terminated. We should definitely clean up that interval, or it will remain in the scheduler to be executed until the process is terminated.

The `v0.4.13` fix, unfortunately, in my tests, doesn't seem to solve the 'not opened' error, because it is actually the call to `ws.ping()` that is causing the exception, and not the call to `ws.terminate()`. Unless, since @dakovi hasn't reopened this, I have truly lost my mind? 😨 And either you or @dakovi can help me piece it back together? lol

I'm going to quickly bang out a fix for the clearing of the interval now though, which should kill two birds with one stone, and we won't have to worry about functions being called on the, now terminated, `WebSocket`.

**Comment by jaggedsoft** [comment]
Sounds great, wasn't thinking about that case. I'm glad there's fresh eyes looking at this stuff. Thanks guys!!

**Comment by dakovi** [comment]
Yeah, I've seen the "not opened" error yesterday after running the updated script for 180 minutes again (for no obvious reason since my script wasn't terminating or even doing anything) - I guess there was some kind of connection problem on Binance's side which let the 'not opened' problem reappear.

Today it's running since 8 hours without any incident.

**Comment by jaggedsoft** [comment]
There's a few hiccups while we transition here, but I believe we are going to end up with the most bulletproof Binance integration there is. When we're finished working on some improvements, our goal is get as close to 100% uptime as possible. Thanks for helping us achieve that goal

**Comment by dakovi** [comment]
Quick question which came to my mind while thinking about the problem:

I am in a kind of middle ground between "want to control and terminate my websockets manually without auto reconnect" (reconnect false) and "would appreciate automatic reconnections and heartbeat checks on unwanted Binance errors and connection losses" (need reconnect true).

Do you see any possibility to separate the reconnect true (heartbeat etc) features from actively terminated websocket connections and just use it for "unwanted" disconnects as described above?

**Comment by keith1024** [comment]
I agree. As a separate, "enhancement request" issue from this one, but I am all for a future release where a manually called `websockets.terminate()` overrides the `reconnect` option, and you can rest easy that unexpected disconnects will be handled by the API.
