### ISSUE TITLE
how to close websocket instance

### ISSUE THREAD

**Issue by includeleec** [jaggedsoft/node-binance-api#13]
can expose close websocket instance method?

**Comment by jaggedsoft** [comment]
Good idea, and thank you for the suggestion. Unfortunately this problem is a bit more challenging than I expected.
The best way I can think to tackle this problem is to store a reference to each `ws` object:
```js
// List all endpoints
let endpoints = binance.websockets.subscriptions();
for ( let endpoint in endpoints ) {
	console.log(endpoint);
	//binance.websockets.terminate(endpoint);
}
```

Now you can terminate each websocket endpoint by the id:
```js
binance.websockets.terminate('ethbtc@kline_1m');
```
But you must disable automatic websocket reconnection for this to work:

```js
binance.options({
	'APIKEY': '<your key>',
	'APISECRET': '<your secret>',
	'reconnect': false
});
```

These features are live in the latest version `v0.2.8`
