### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by keesgeel** [jaggedsoft/node-binance-api#141]
Hi there!

When tracking 4 or more pairs through webSocket (binance.websockets.depth) I get the following exception. Anyone knows how I can prevent this?

> ~/project/node_modules/node-binance-api/node-binance-api.js:897
>                         context.messageQueue = context.messageQueue.filter(depth => depth.u > context.snapshotUpdateId);
>                                                                     ^
> 
> TypeError: Cannot read property 'filter' of undefined

**Comment by keith1024** [comment]
Hi,

Just to confirm, you mean `binance.websockets.depthCache` right, and not `binance.websockets.depth`?

I find these undefined `messageQueue` errors most bizarre, as the array is always created first before subscribing to the data stream, and retrieving the snapshot.

I'm just trying to get a better picture of the root cause of these errors, because checking for the existence of the array is only masking the cause.

How many calls in total do you make to `websockets.depthCache`? ie. How many separate streams do you have open to market depths? What `symbols` are you passing to each call?

**Comment by keesgeel** [comment]
Hi @keith1024 - Thanks for your response!

Indeed, I ment `binance.websockets.depthCache`. I actually just found the issue, it has nothing to do with the amount. When you track the same pair more then once, this error is triggered.

**Comment by keith1024** [comment]
Sorry for the massive delay @keesgeel. Yeah, I was thinking it was when tracking a pair more than once. It will only happen if you start tracking the same pair again almost immediately after the last call to track that pair. I will keep this in mind and implement a guard against it as soon as I have the time.

**Comment by dmzoneill** [comment]
this is fixed a number of commits back
