### ISSUE TITLE
Websocket periodical writefile ? 

### ISSUE THREAD

**Issue by t-westwood** [jaggedsoft/node-binance-api#172]
Hey dude, Im using the code below, and this is continuously writing files. The write file is working perfectly, but I'm trying to access these files every 5 minutes or so and check data etc,  but im getting errors quite often (think its because im trying to read a file whilst its in process of being written.) So i diddnt know if there was a way to write file (one for every pair) every few minutes. 

im using the indicators library you suggested in a previous topic, instead of keep saving the candlestick data to a new file.  Is there a way to incorporate the indicators (eg, RSI) directly in the webstream?.  

Thanks dude!

`const fs = require('fs');
const binance = require('node-binance-api')

// get all markets, volume, daily change
binance.prevDay(false, (error, prevDay) => {
	let markets = [];
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		if ( obj.volume < 1 ) continue; // perform any filtering you want
		console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
		if ( symbol.substr(-3) !== 'BTC' ) continue; // filter BTC only, etc
		markets.push(symbol);
	}
	console.info("Total markets: ", markets.length);
	let interval = '5m';
	binance.websockets.chart(markets, interval, (symbol, interval, chart) => {	
		let output = [], tick;
		const range = Object.keys(chart).slice(-250);
		for ( let time of range ) {
			tick = chart[time];
			tick.timestamp = Number(time);
			let timestamp = new Date(tick.timestamp).toLocaleString();
			console.log(timestamp+" "+symbol+": $"+tick.close+"\t high: $"+tick.high+"\t low: $"+tick.low);
			output.push(tick);
		}
				fs.writeFile("charts/"+symbol+".json", JSON.stringify(output, null, 4), (err)=>{});
	});
});`

**Comment by broburns** [comment]
I can't help with using the indicators, but in regards to your issue with the files, you can try wrapping your writeFile() and whatever you're using to access the file into a timer function or use a cron job. For example, write something that keeps track of the time outside of the websocket function, and then inside of the websocket callback function use an if() statement to compare the current time of each new tick and your timer function to save the output array to the file every so often. You can then use your timer to access the file at the interval you need without having to worry about it failing due to it already being accessed by the writeFile(). Hope that helps.

**Comment by jaggedsoft** [comment]
Simple example of using TA
```js
const TA = require('technicalindicators');
binance.websockets.chart("BNBBTC", "1h", (symbol, interval, chart) => {
  let ohlc = binance.ohlc(chart);
  let rsi = TA.RSI.calculate({values:ohlc.close, period:14});
  let last_rsi = rsi[rsi.length - 1];
  console.log("RSI: "+last_rsi);
});
```

As for reading the json while it's being written, I am familiar with the problem because I have the same issue myself. Wish I had a solution for you
