### ISSUE TITLE
Partial depth in combined stream not showing full data

### ISSUE THREAD

**Issue by fngrz** [jaggedsoft/node-binance-api#199]
When using a the .combinedStream, partial depth e.g. (depth20) only shows bids and asks. The problem is that if you combine depths for more than one symbol, you don't know which depth comes from where.

So let's say I wanted to get the ticker and depth20 for EOSBTC and QTUMBTC, I would be able to know which price ticker was for each pair, but not which depth result.

**Comment by jaggedsoft** [comment]
Did you get this resolved? I understand the problem and would like to implement a solution

**Comment by fngrz** [comment]
@jaggedsoft no I didn't. I did check the Binance API (https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#partial-book-depth-streams) and noticed that the info wasn't passed either. Is there a way to pick it up from the variable you're passing and sticking it in the results? I'm not experienced enough to get it done otherwise I'd have tried

**Comment by jaggedsoft** [comment]
I'm prepping for moving out of the country so I don't have a lot of development time lately
But the problem is here https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L513
on line 515 we are passing json.data and I think what we really should be doing is passing `json` so we have access to the rest of the properties

Then this will also require a change to handleDepthStreamData on line 1687, will need to change that line to this: `let handleDepthStreamData = function(json) {` (change 'depth' parameter to 'json')
then `const depth = json.data;` on the following line

**Comment by fngrz** [comment]
@jaggedsoft yup. it worked... somewhat. now need to parse the result so it's readable (but it's right there)
