### ISSUE TITLE
How To Handle 429 Response Code?

### ISSUE THREAD

**Issue by hugeprestigellc** [jaggedsoft/node-binance-api#263]
Hi there, apologies again if this is the wrong place to ask this. I'm writing a trading app using this API. There's going to be times when a lot of buy/sell orders get fired off. I don't want to have my IP address banned obviously.

When it comes to 429 responses, what is the way to handle that? For example, using marketBuy(pair, roundedNumber, (error, response) =>...)

Would that 429 response be in the error object? Or the response object? Hope the question makes sense. Thanks

**Comment by jaggedsoft** [comment]
The error.statusCode parameter will be set. So probably something like this:
`if ( error && typeof error.statusCode !== "undefined" && error.statusCode == 429 )`

I have never run into a 429 error because I try not to make an excessive amount of requests
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information
```js
{ "rateLimits": [{
      "rateLimitType": "REQUESTS_WEIGHT",
      "interval": "MINUTE",
      "limit": 1200
    }, {
      "rateLimitType": "ORDERS",
      "interval": "SECOND",
      "limit": 10
    }, {
      "rateLimitType": "ORDERS",
      "interval": "DAY",
      "limit": 100000
    }
  ]
}
```

**Comment by hugeprestigellc** [comment]
Thanks for the quick response! I'll try something like that. 

What do you think is an excessive amount of requests?

**Comment by jaggedsoft** [comment]
Two per second or less

**Comment by hugeprestigellc** [comment]
Thanks, this was very insightful.
