### ISSUE TITLE
Question: what is the function of the price when placing a stop-loss

### ISSUE THREAD

**Issue by MaPoLom** [jaggedsoft/node-binance-api#331]
Hi,

Probably a simple question but what is the meaning of the price in the stop-loss example

```
// When the stop is reached, a stop order becomes a market order
// Note: You must also pass one of these type parameters:
// STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT
let type = "STOP_LOSS";
let quantity = 1;
let price = 0.069;    <----  What is this doing here?
let stopPrice = 0.068; <- this one I understand..
binance.sell("ETHBTC", quantity, price, {stopPrice: stopPrice, type: type});
```
A bit of in depth is appreciated..

Thank you,

MauPoLom

**Comment by bmino** [comment]
That price parameter is not used when specifying a type of `STOP_LOSS`

The parameter is there because the binance.sell() method can be called for a couple different execution types. Executions such as `LIMIT`, `STOP_LOSS_LIMIT`, or `TAKE_PROFIT_LIMIT` will need that parameter. You could pass in `null` and be fine in your example
