### ISSUE TITLE
Order status update..

### ISSUE THREAD

**Issue by beratuslu** [jaggedsoft/node-binance-api#335]
Hello
Is it possible to get trade updates with websocket when they are "filled"?

Thanks.

**Comment by jaggedsoft** [comment]
Yeah it's not a bulletproof implementation but you can search for "filled" on this page
https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md

**Comment by beratuslu** [comment]
What you mean buy "it's not a bulletproof implementation" because it is crucial for my application. A question.  It looks like balance update working well. So is it making sense checking order statuses on "balance update" if its working with flaw?

**Comment by jaggedsoft** [comment]
I do not rely on this data because there have been times the websocket enters a zombie state where it stops sending new data. The solution would be to automatically disconnect it if you do not receive data in a certain time period. This may or may not have already been implemented

As a fallback, perhaps design it in a way where you can double check with periodic results using the REST API

**Comment by beratuslu** [comment]
@jaggedsoft my whole application relies on below function it isn't reliable?
```
binanceInstance.websockets.userData(balance_update, execution_update);
```
