### ISSUE TITLE
Use this library directly in the browser?

### ISSUE THREAD

**Issue by webqap** [jaggedsoft/node-binance-api#38]
Hi. What would be the best way to use this library in the browser?

**Comment by jaggedsoft** [comment]
Not possible. No exchanges allow connections to their API via the browser or plugins due to CORS/cross origin security issues

**Comment by jaggedsoft** [comment]
https://github.com/binance-exchange/node-binance-api/issues/27

**Comment by webqap** [comment]
Ah yes that is true. 

Though I think you can bypass the CORS issues by creating a custom dns/hosts entry on your local machine. For example:

cors.binance.com 127.0.0.1

Then the browser wouldn't complain anymore. 

Thanks for getting back!

**Comment by sadburai** [comment]
hi, I was wondering today, how to implement the library in my browser. Since this post is 3 years, old, is this still not possible?

**Comment by jaggedsoft** [comment]
it can be done using electron and vue i believe, and there's a couple new executable build tools as well. haven't really stayed on top of this but I have done it.

You can also make a CORS wrapper on a webserver (or serverless) to act as a proxy since binance forbids browser requests except on binance.com. This way you can run without electron, in the native browser, and still make connections. I started on this project but only got a few functions and websocket working. I can share the source, but not my proxy. Basically just need the data from Binance without going through binance.com

**Comment by jaggedsoft** [comment]
for nginx there are reverse websocket proxies as well
and I managed to get one working on apache

Reverse proxy example: instead of accessing `wss://stream.binance.com/klines/btcusdt` I access `wss://mydomain.com/stream/klines/btcusdt` for example, and I don't even have a https certificate since cloudflare handles that for me (flexible ssl)

**Comment by sadburai** [comment]
ok, thank you!  amI still trying to figure out if it's possible to create one single javascript file from the node package that I could embed in a <script> tag.  So I think your solutions is above my skill level then.

**Comment by jaggedsoft** [comment]
yeah every step of the way is a challenge, unless..

you use visual studio code and electron. it just takes a little bit of reading, nothing too complicated.

you have to edit your project build settings to compile the exe every time you save, and thats it. everything works with no limitations https://cmatskas.com/creating-electron-apps-with-visual-studio-code/

theres also a quick start, havent tried it https://www.c-sharpcorner.com/article/getting-started-with-electron-js-with-visual-studio-code/

**Comment by sadburai** [comment]
Thanks, I really appreciate your quick help! I thought about using Electron already, and now I have a good place to start.

**Comment by jaggedsoft** [comment]
awesome, feel free to post here if you need help with anything or get stuck 💯 cheers friend

**Comment by sadburai** [comment]
hi again. So I tried to use websockets in my developer console and on my client side javascript file, and it worked flawlessly. I had no CORS errors and could see all my orders through the Websocket:

- Streaming Candlestick data:
const conn = new WebSocket(`wss://stream.binance.com:9443/ws/btcusdt@kline_1m`);

- Streaming personal UserData:
1.) get the <listenKey>: via POST /api/v3/userDataStream
2.) const conn = new WebSocket(`wss://stream.binance.com:9443/ws/<listenKey>`);
 
 conn.onmessage = (event) => console.log(event.data);

What am I missing here? Does that mean they changed the API, so that it's possible to use websockets directly on the client side without CORS issues now?

**Comment by jaggedsoft** [comment]
yeah it appears so, I tried it on a webpage and it worked just fine. Something was likely changed within the last 90 days.
Good news! this data should be publicly accessible anyway. it's much simpler and faster like this

I wanted to record the trade stream and make my own 1 second, 5 second, 30 second charts

**Comment by jaggedsoft** [comment]
more importantly, you don't need to proxy normal API requests anymore either.

```js
let ethusdt = await fetch("https://api.binance.com/api/v3/ticker/bookTicker?symbol=ETHUSDT");
console.info(await ethusdt.json());
```

this seems to work just fine now as well. which is good because this is the reason I couldn't publish the browser version of the library, since someone would need to set up a complicated reverse proxy. Now it's easy 😀

**Comment by jaggedsoft** [comment]
Browser friendly work-in-progress version of this library: https://github.com/jaggedsoft/node-binance-api/blob/master/examples/binanceStreams.js
Live demo https://liquidity.ltd/
Second demo https://liquidity.ltd/js/websocket.html

Vanilla method example for trade stream (no library)
```js
    let ws = new WebSocket("wss://stream.liquidity.ltd/spot/btcusdt@aggTrade")
    ws.onmessage = ( evt ) => {
        let payload = JSON.parse(evt.data); //s: symbol, p: price
        console.info(`${payload.s}: ${payload.p)`);
    };
```

**Comment by sadburai** [comment]
thanks!

Did you figure out how to send a normal API request that requires an API-Key or API signature from the browser?

I tried, but I think that this is not possible due to CORS. I made a `fetch` request to receive my ListenKey in the browser but it does not work

My Request using fetch (with client side javascript in Chrome):
` {
        method: "POST",
        path: "/api/v3/userDataStream",
        headers: {
          "X-MBX-APIKEY": api_key,
        },
      }`

Response from API:
`Access to fetch at 'https://api.binance.com/api/v3/userDataStream' from origin 'http://localhost:5500' has been blocked by CORS policy: Request header field x-mbx-apikey is not allowed by Access-Control-Allow-Headers in preflight response.`

Can you confirm this?
