### ISSUE TITLE
Add better support for test mode with Binance Futures

### ISSUE THREAD

**Issue by stepanmas** [jaggedsoft/node-binance-api#420]
If I call `futuresLeverageBracket('BTCUSDT')`, then I get the error.
I can fix it use next condition, but I not sure what it is good idea.
![image](https://user-images.githubusercontent.com/6086962/80908445-e9e0ec80-8d30-11ea-8365-a32d46bcb0f9.png)

**Comment by jaggedsoft** [comment]
Hmm, why can I not reproduce this bug?

```js
    const binance = new Binance( `${ path }futures.json` );
    await binance.useServerTime();
    console.info( await binance.futuresLeverageBracket( "BTCUSDT" ) );
```

**Comment by stepanmas** [comment]
> Hmm, why can I not reproduce this bug?
> 
> ```js
>     const binance = new Binance( `${ path }futures.json` );
>     await binance.useServerTime();
>     console.info( await binance.futuresLeverageBracket( "BTCUSDT" ) );
> ```

Test it, please.
![image](https://user-images.githubusercontent.com/6086962/80912742-31c33c00-8d50-11ea-9e06-f1263c92b309.png)

**Comment by jaggedsoft** [comment]
1. Binance.options should be passed like this. Remove `opt:`

```js
new Binance().options({
  APIKEY: '<key>',
  APISECRET: '<secret>'
});
```

2. This might only happen when test mode is set to true. Will require further testing

**Comment by stepanmas** [comment]
1. `opt` is tooltip from IDE.
2. Test mode or not, need to fix it. I use your library in my application.

**Comment by jaggedsoft** [comment]
Thanks for your report, this was fixed in the latest version https://github.com/jaggedsoft/node-binance-api/commit/0410389b3421496c17b9f96d4f271be4f72db287

I can issue a new release now if it will help you, otherwise it will be a few days

promiseRequest:
`if ( flags.type === 'SIGNED' || flags.type === 'TRADE' || flags.type === 'USER_DATA' || ( Binance.options.test && flags.type === 'MARKET_DATA' ) ) {`

**Comment by stepanmas** [comment]
Thank you, no hurry with release.

**Comment by joelrich** [comment]
Yesterday, Binance deployed a new version of Binance Futures, which broke the leverageBracket API and is therefore not backward compatible. Pretty amazing for an exchange which trades billions of dollars daily...

Anyway, It seems like they deployed this first on testnet, which is why this issue was reported before it started happening on production.

From changelog (https://binance-docs.github.io/apidocs/futures/en/#change-log):
```
    Endpoint GET /fapi/v1/leverageBracket is changed as "USER-DATA". It need to be signed, and timestamp is needed.
```
So yeah, MARKET_DATA should be changed to USER_DATA for leverageBracket. This will fix it both on testnet and production.
