### ISSUE TITLE
Getting LOT_SIZE error when trying to sell crypto

### ISSUE THREAD

**Issue by r0l-hub** [jaggedsoft/node-binance-api#465]
I'm getting this error: {"code":-1013,"msg":"Filter failure: LOT_SIZE"}

The code is:
binance.sell("BTCBUSD", 0.00078937, 9526.03, {type:'LIMIT'}, (error, response) => {
                 ...
                })

Why I am getting this error? 

Lot size for this pair is:
"filterType": "LOT_SIZE",
"minQty": "0.00000100",
"maxQty": "9000.00000000",
"stepSize": "0.00000100"

**Comment by jaggedsoft** [comment]
Looks like binance is incorrectly returning the error as lot_size when it's actually due to MIN_NOTIONAL
![image](https://user-images.githubusercontent.com/4283360/88464749-8f81a300-cebd-11ea-97d3-eff2adb1ef14.png)

Try selling that same amount using the web interface and it will tell you that the minimum order size is $10
