### ISSUE TITLE
Futures WebSocket reconnect error: reconnect is not a function

### ISSUE THREAD

**Issue by Kuzmich100kM** [jaggedsoft/node-binance-api#499]
This error often appears and the socket does not reconnect. What could be the reason?

![not_reconnect](https://user-images.githubusercontent.com/46998842/93140405-0f243500-f6eb-11ea-89b3-e343f7b60030.jpg)

**Comment by arenddeboer** [comment]
I think this happens because userFutureData() is missing a reconnect callback.
If you look at userMarginData() https://github.com/jaggedsoft/node-binance-api/blob/c73dd18c52ea8ad8ab3f62b3b98f9af27c2b8fdd/node-binance-api.js#L4916 you see it has 


```
let reconnect = () => {
                    if ( Binance.options.reconnect ) userMarginData( callback, execution_callback, subscribed_callback );
                };
``` 

userFutureData() does not have this and instead passes a boolean as the reconnect function.
eg:
userMarginData()
```const subscription = subscribe(Binance.options.listenMarginKey, userMarginDataHandler, reconnect)```

vs
userFutureData()
```const subscription = futuresSubscribe(Binance.options.listenFutureKey, userFutureDataHandler, Binance.options.reconnect)```

Will have to test this out and submit a PR if this is indeed the issue.

**Comment by arenddeboer** [comment]
I think I was able to fix this, I added it to an existing PR: https://github.com/jaggedsoft/node-binance-api/pull/501
