### ISSUE TITLE
depthCache limit question

### ISSUE THREAD

**Issue by jsappme** [jaggedsoft/node-binance-api#56]
the following code:

```
binance.websockets.depthCache([pair], (symbol, depth) => {
			var bids = binance.sortBids(depth.bids)
			var asks = binance.sortAsks(depth.asks)
console.log(symbol + " " + _.values(asks).length + " / " + _.values(bids).length )
		}, 10);
```
produces

```
ETHBTC 63 / 61
NEOBTC 45 / 66
WTCBTC 41 / 59
LTCBTC 53 / 57
BCCBTC 32 / 31
MCOBTC 27 / 18
```
the size of bids and asks keeps increasing over time. is it intended? should bids and asks size auto resized to the input limit?

**Comment by jaggedsoft** [comment]
Probably better to do something like this and not set a limit

```js
binance.websockets.depthCache([pair], (symbol, depth) => {
			var bids = binance.sortBids(depth.bids)
			var asks = binance.sortAsks(depth.asks)
console.log(symbol + " " + _.values(asks).length + " / " + _.values(bids).length )
		});
```

Here is what I do
```js
binance.websockets.depthCache(["BTCUSDT"], function(symbol, depth) {
	let max = 10; // Only show the 10 best bids / asks (optional)
	let bids = binance.sortBids(depth.bids, max);
	let asks = binance.sortAsks(depth.asks, max);
	console.log(binance.reverse(asks)); // print asks
	console.log("ask: ", binance.first(asks));
	console.log("bid: ", binance.first(bids));
	console.log(bids); // print bids
});
```
![image](https://user-images.githubusercontent.com/4283360/34911325-4ae87c1e-f87d-11e7-8703-0b0dc7d354b6.png)

The difference here is we are accepting the default limit of 500 entries, but we are taking only the best 10 bids/asks out of that for display purposes

**Comment by jsappme** [comment]
nice one

**Comment by jsappme** [comment]
```
var bids = binance.sortBids(depth.bids, 100)
console.log(_.values(bids).length)   => 101
```

**Comment by jaggedsoft** [comment]
Thanks, fixed in next version
`if ( ++count > max ) break;`

switched to

`if ( ++count >= max ) break;`

**Comment by msalvatti** [comment]
> 

@jaggedsoft 

Please, what's the best way to manage the bookdepth with this lib?
I noticed that the depthCache object has no size control, it is always growing, only if the amount is 0 that is removed.
I imagine it is correct, because that way you can have the entire book in cache, but the object will always be growing, with no size limit?
Is there any way to control this depthCache object size? I will have a lot of symbols being analyzed and a lot of objects always growing doesn't look good.
I saw that it has a function to clear the cache, but then I lose all data.
I would like to do something like bids/asks sort, where I can get the size I need.
Is there a way to do this?

Thanks.
