### ISSUE TITLE
Use Array instead of Object for DepthCache

### ISSUE THREAD

**Issue by tsujp** [jaggedsoft/node-binance-api#7]
It's my understanding that Objects are required to be sorted, nor guaranteed to return sorted. Should you use an Array to hold sorted asks/bids instead?

**Comment by jaggedsoft** [comment]
Thank you for your suggestion!
An Object was used because it would use less processing power to keep the key/value store up to date, I didn't want lag in case I subscribed via websocket to 30+ different depth caches, then it would have to loop through several thousand entries multiple times per second in order to keep each one up to date, thus causing latency which is not desired for financial applications.

With objects, every time there is a websocket update it is rather trivial to update the depth cache. No sorting is required except for display purposes. To get the best bid/ask, you can just use the unsorted object array for maximum speed:
```js
binance.websockets.depthCache(["BNBBTC"], function(symbol, depth) {
	console.log(symbol+" depth cache update");
	console.log("ask: " + binance.min(depth.asks));
	console.log("bid: " + binance.max(depth.bids));
	//console.log(depth); // print the entire depth cache
});
```

![image](https://user-images.githubusercontent.com/4283360/32147486-53564aa2-bca5-11e7-8019-566e6bccc568.png)
Example with sorting: (like picture)
```js
binance.websockets.depthCache(["BNBBTC"], function(symbol, depth) {
	let max = 9; // Only show the 9 best bids / asks (optional)
	let baseVolume = true; // Show results in BTC/ETH/USDT value (optional)
	let bids = binance.sortBids(depth.bids, max, baseVolume);
	let asks = binance.sortAsks(depth.asks, max, baseVolume);
	console.log("asks", binance.reverse(asks));
	console.log("bids", bids);
	let askvol = binance.sum(Object.values(asks));
	let bidvol = binance.sum(Object.values(bids));
	let ratio = binance.percent(bidvol, bidvol + askvol);
	console.log("ask: " + binance.first(asks)+"\tvolume: "+askvol.toFixed(3));
	console.log("bid: " + binance.first(bids)+"\tvolume: "+bidvol.toFixed(3));
	console.log("buy ratio: " + ratio.toFixed(2) + "%");
});
```

Sorting should also be used to determine the nearest support & resistance levels.
If you require the depth cache to be returned as an array I can help you. Just let me know

**Comment by jaggedsoft** [comment]
Often times depth data is required to be in array format. For example, when drawing charts:
https://bfxdata.com/mobileSite/mobileGraphMarketDepthBTCUSD.php
Data format: https://bfxdata.com/json/marketDepthBidsBTCUSD.json

For this reason I have added an `array` function to convert an object into an array:
```js
binance.depth("BNBBTC", function(depth, symbol) {
	console.log(symbol+" bids", binance.array(depth.bids));
	console.log(symbol+" asks", binance.array(depth.asks));
});
```

This code will be included in the next release
